Repository CorgiTeamIncorporated/graph-image-segmentation, pull requests merged in 2021-05, with the labels that each got.

#4 Issues/1
  .gitignore
  main.py
  push_relabel.py
  requirements.txt
Labels: enhancement

#5 Issues/2
  .gitignore
  push_relabel.py
Labels: enhancement

#6 global relabeling heuristic implementation
  push_relabel.py
Labels: enhancement

#18 refactor push_relabel test
  tests/test_01_push_relabel.py
Labels: enhancement, tests

#19 highest-label selection rule optimization
  push_relabel.py
Labels: algorithm, enhancement

#21 add return of s-t cut in get_max_flow function
  push_relabel.py
  tests/test_01_push_relabel.py
  tests/test_02_s_t_cut.py
  tests/utils.py
Labels: algorithm, new feature

#25 add GUI implementation
  main.py
Labels: app, new feature

#26 segmentation first iteration implementation
  .gitignore
  algo/graph_utils.py
  algo/image_segmentation.py
  requirements.txt
  segmentation_test.py
  tests/test_01_push_relabel.py
  tests/test_02_s_t_cut.py
Labels: algorithm, new feature

#28 add interactive segmentation implementation
  algo/graph_utils.py
  algo/image_segmentation.py
  requirements.txt
  segmentation.py
Labels: algorithm, enhancement

#30 gui reworked
  main.py
Labels: app, enhancement

#32 gui and segmentation integrated
  main.py
Labels: algorithm, app, enhancement

#33 add segmentation tests and metrics
  .gitignore
  algo/__init__.py
  algo/tests/__init__.py
  algo/tests/push_relabel_test_inputs/test_1.txt
  algo/tests/push_relabel_test_inputs/test_2.txt
  algo/tests/push_relabel_test_inputs/test_3.txt
  algo/tests/push_relabel_test_inputs/test_4.txt
  algo/tests/push_relabel_test_inputs/test_5.txt
  algo/tests/push_relabel_test_inputs/test_6.txt
  algo/tests/push_relabel_test_inputs/test_d1.txt
  algo/tests/push_relabel_test_inputs/test_d2.txt
  algo/tests/push_relabel_test_inputs/test_d3.txt
  algo/tests/push_relabel_test_inputs/test_d4.txt
  algo/tests/push_relabel_test_inputs/test_d5.txt
  algo/tests/push_relabel_test_inputs/test_rd01.txt
  algo/tests/push_relabel_test_inputs/test_rd02.txt
  algo/tests/push_relabel_test_inputs/test_rd03.txt
  algo/tests/push_relabel_test_inputs/test_rd04.txt
  algo/tests/push_relabel_test_inputs/test_rd05.txt
  algo/tests/push_relabel_test_inputs/test_rd06.txt
  algo/tests/push_relabel_test_inputs/test_rd07.txt
  algo/tests/push_relabel_test_inputs/test_rl01.txt
  algo/tests/push_relabel_test_inputs/test_rl02.txt
  algo/tests/push_relabel_test_inputs/test_rl03.txt
  algo/tests/push_relabel_test_inputs/test_rl04.txt
  algo/tests/push_relabel_test_inputs/test_rl05.txt
  algo/tests/push_relabel_test_inputs/test_rl06.txt
  algo/tests/push_relabel_test_inputs/test_rl07.txt
  algo/tests/push_relabel_test_inputs/test_rl08.txt
  algo/tests/push_relabel_test_inputs/test_rl09.txt
  algo/tests/push_relabel_test_inputs/test_rl10.txt
  algo/tests/test_01_push_relabel.py
  algo/tests/test_02_s_t_cut.py
  algo/tests/test_03_segmentation.py
  algo/tests/utils.py
  algo/utils.py
  requirements.txt
Labels: algorithm, new feature, tests

#34 radius slider implemented
  main.py
Labels: app, enhancement

#37 add ground truth display and metrics to GUI
  algo/utils.py
  main.py
Labels: app, new feature
